### ISSUE TITLE
Zip corrupted?

### ISSUE THREAD

**Issue by ottopic** [hansemannn/titanium-dark-mode#1]
Hello,
I'm tring to download this dist or building it from source, but after download or completed run ti.darkmode-iphone.1.0.0.zip is not unzippable. Any idea? 😕

**Comment by ottopic** [comment]
Repairing it with zip -FF ti.darkmode-iphone-1.0.0.zip --out ti.darkmode-iphone-1.0.0bis.zip
the result is: 
zip warning: Missing end (EOCDR) signature - either this archive
                     is not readable or the end is damaged

**Comment by hansemannn** [comment]
@ottopic I just updated the zip!

**Comment by ottopic** [comment]
@hansemannn wonderful! Many thanks. :)

**Comment by ottopic** [comment]
@hansemannn sorry, but you have uploaded Apple Sign In!

**Comment by hansemannn** [comment]
mehhh, wrong repo. 1 sec

**Comment by hansemannn** [comment]
Try now please

**Comment by ottopic** [comment]
> Try now please

That's ok! Thank you for your assistance.
