### ISSUE TITLE
Add flag isDarkMode

### ISSUE THREAD

**Issue by parnanzio** [hansemannn/titanium-dark-mode#2]
Great plugin, but I think a simple `isDarkMode()` function would help a lot.

Example: we could extend the `Alloy.CFG.colors` with the `Alloy.CFG.darkColors` object. Does this request makes any sense?

**Comment by hansemannn** [comment]
You can use the new `Ti.App.iOS.userInterfaceStyle` property and  `traitcollectionchange` event in 8.2.0 as following:
```js
// Initial mode
let darkModeEnabled = Ti.App.iOS.userInterfaceStyle === Ti.App.iOS.USER_INTERFACE_STYLE_DARK;

// Interactive updates
Ti.App.iOS.addEventListener('traitcollectionchange', () => {
	darkModeEnabled = Ti.App.iOS.userInterfaceStyle === Ti.App.iOS.USER_INTERFACE_STYLE_DARK;
});
```
